// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file picture.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _PICTURE_H_
#define _PICTURE_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(picture_SOURCE)
#define picture_DllAPI __declspec( dllexport )
#else
#define picture_DllAPI __declspec( dllimport )
#endif // picture_SOURCE
#else
#define picture_DllAPI
#endif
#else
#define picture_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}


/*!
 * @brief This class represents the structure picture defined by the user in the IDL file.
 * @ingroup PICTURE
 */
class picture
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport picture();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~picture();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object picture that will be copied.
     */
    eProsima_user_DllExport picture(const picture &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object picture that will be copied.
     */
    eProsima_user_DllExport picture(picture &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object picture that will be copied.
     */
    eProsima_user_DllExport picture& operator=(const picture &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object picture that will be copied.
     */
    eProsima_user_DllExport picture& operator=(picture &&x);

    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(uint32_t _index);

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const;

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index();

    /*!
     * @brief This function sets a value in member size
     * @param _size New value for member size
     */
    eProsima_user_DllExport void size(uint32_t _size);

    /*!
     * @brief This function returns the value of member size
     * @return Value of member size
     */
    eProsima_user_DllExport uint32_t size() const;

    /*!
     * @brief This function returns a reference to member size
     * @return Reference to member size
     */
    eProsima_user_DllExport uint32_t& size();

    /*!
     * @brief This function copies the value in member note
     * @param _note New value to be copied in member note
     */
    eProsima_user_DllExport void note(const std::string &_note);

    /*!
     * @brief This function moves the value in member note
     * @param _note New value to be moved in member note
     */
    eProsima_user_DllExport void note(std::string &&_note);

    /*!
     * @brief This function returns a constant reference to member note
     * @return Constant reference to member note
     */
    eProsima_user_DllExport const std::string& note() const;

    /*!
     * @brief This function returns a reference to member note
     * @return Reference to member note
     */
    eProsima_user_DllExport std::string& note();
    /*!
     * @brief This function copies the value in member buffer
     * @param _buffer New value to be copied in member buffer
     */
    eProsima_user_DllExport void buffer(const std::vector<uint8_t> &_buffer);

    /*!
     * @brief This function moves the value in member buffer
     * @param _buffer New value to be moved in member buffer
     */
    eProsima_user_DllExport void buffer(std::vector<uint8_t> &&_buffer);

    /*!
     * @brief This function returns a constant reference to member buffer
     * @return Constant reference to member buffer
     */
    eProsima_user_DllExport const std::vector<uint8_t>& buffer() const;

    /*!
     * @brief This function returns a reference to member buffer
     * @return Reference to member buffer
     */
    eProsima_user_DllExport std::vector<uint8_t>& buffer();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const picture& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    uint32_t m_index;
    uint32_t m_size;
    std::string m_note;
    std::vector<uint8_t> m_buffer;
};

#endif // _PICTURE_H_