// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file orderInfo.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _ORDERINFO_H_
#define _ORDERINFO_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(orderInfo_SOURCE)
#define orderInfo_DllAPI __declspec( dllexport )
#else
#define orderInfo_DllAPI __declspec( dllimport )
#endif // orderInfo_SOURCE
#else
#define orderInfo_DllAPI
#endif
#else
#define orderInfo_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}


/*!
 * @brief This class represents the structure orderInfo defined by the user in the IDL file.
 * @ingroup ORDERINFO
 */
class orderInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport orderInfo();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~orderInfo();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object orderInfo that will be copied.
     */
    eProsima_user_DllExport orderInfo(const orderInfo &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object orderInfo that will be copied.
     */
    eProsima_user_DllExport orderInfo(orderInfo &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object orderInfo that will be copied.
     */
    eProsima_user_DllExport orderInfo& operator=(const orderInfo &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object orderInfo that will be copied.
     */
    eProsima_user_DllExport orderInfo& operator=(orderInfo &&x);

    /*!
     * @brief This function sets a value in member orderNumber
     * @param _orderNumber New value for member orderNumber
     */
    eProsima_user_DllExport void orderNumber(uint32_t _orderNumber);

    /*!
     * @brief This function returns the value of member orderNumber
     * @return Value of member orderNumber
     */
    eProsima_user_DllExport uint32_t orderNumber() const;

    /*!
     * @brief This function returns a reference to member orderNumber
     * @return Reference to member orderNumber
     */
    eProsima_user_DllExport uint32_t& orderNumber();

    /*!
     * @brief This function sets a value in member partNumber
     * @param _partNumber New value for member partNumber
     */
    eProsima_user_DllExport void partNumber(uint32_t _partNumber);

    /*!
     * @brief This function returns the value of member partNumber
     * @return Value of member partNumber
     */
    eProsima_user_DllExport uint32_t partNumber() const;

    /*!
     * @brief This function returns a reference to member partNumber
     * @return Reference to member partNumber
     */
    eProsima_user_DllExport uint32_t& partNumber();

    /*!
     * @brief This function sets a value in member quantity
     * @param _quantity New value for member quantity
     */
    eProsima_user_DllExport void quantity(uint16_t _quantity);

    /*!
     * @brief This function returns the value of member quantity
     * @return Value of member quantity
     */
    eProsima_user_DllExport uint16_t quantity() const;

    /*!
     * @brief This function returns a reference to member quantity
     * @return Reference to member quantity
     */
    eProsima_user_DllExport uint16_t& quantity();

    /*!
     * @brief This function copies the value in member note
     * @param _note New value to be copied in member note
     */
    eProsima_user_DllExport void note(const std::string &_note);

    /*!
     * @brief This function moves the value in member note
     * @param _note New value to be moved in member note
     */
    eProsima_user_DllExport void note(std::string &&_note);

    /*!
     * @brief This function returns a constant reference to member note
     * @return Constant reference to member note
     */
    eProsima_user_DllExport const std::string& note() const;

    /*!
     * @brief This function returns a reference to member note
     * @return Reference to member note
     */
    eProsima_user_DllExport std::string& note();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const orderInfo& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    uint32_t m_orderNumber;
    uint32_t m_partNumber;
    uint16_t m_quantity;
    std::string m_note;
};

#endif // _ORDERINFO_H_